### ISSUE TITLE
Export as PNG

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/interaction-viewer#14]
Export the image as a PNG

**Comment by colin-combe** [comment]
If the user really wants a bitmap image you could use the PrintScreen button. 

Also, I think all the image export stuff should be moved outside interaction-viewer because its not possible to reliably control file downloads entirely on client side (and I think we don't want to, for example, hard code the address of a certain server into the viewer code). See #71

I'm gonna tag as 'wont fix' and close, but add comments if you see this as a live issue
