### ISSUE TITLE
Dissappearing participants when embedded in Complex Portal

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/interaction-viewer#18]
Hi Josh,

Oscar embedded the complex viewer into the Complex Portal. When I double click on the expanded sequence of a protein to collapse it again into a circle, the circle flies off the screen (upwards). It comes back when I use the "auto layout" button Oscar installed. Is that a problem at your or our end?

Birgit

**Comment by colin-combe** [comment]
Hi,

On 13/01/15 15:19, bmeldal wrote:
> Oscar embedded the complex viewer into the Complex Portal. 


Great.

> When I double click on the expanded sequence of a protein to collapse 
> it again into a circle, the circle flies off the screen (upwards). 


Oh... not great.

I think I can explain this - the co-ordinates being clicked on by the 
mouse are being misreported. When you click a stick to change it to a 
circle it also moves to the point you clicked (so that it ends up under 
that point).

There's some mix up to do with coordinates on the whole web page and 
coordinates in the box containing the viewer. This is what's causing 
them to fly off the screen.

I can fix this, I've seen it in the crosslink-viewer also. I'll wait 
until after tomorrow's meeting (so we have a chance to discuss our plan 
re. the various branches).


> It comes back when I use the button Oscar installed. Is that problem 
> at your or our end?

Its a problem in the viewer, not the Complex Portal web page.

Colin

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
Closing - they no longer fly off screen
