### ISSUE TITLE
Browser freezes when is displaying a huge complex

### ISSUE THREAD

**Issue by maitesin** [MICommunity/interaction-viewer#24]
When it is trying to display a huge complex (184 participants) it freezes trying to find the position for them.

You can see one example here: http://wwwdev.ebi.ac.uk/intact/complex/details/EBI-9691559

There is something we can do about it? Stop the animation at the beginning to relocate the nodes?

**Comment by colin-combe** [comment]
Well, it didn't completely freeze  but admittedly it was taking a 
while... ;-)

I've tried to reduce the start up time, it is perhaps about a third of 
what it was previously but this may still be too long.

In the case of EBI-9691559 there are other problems - the resulting 
diagram is fairly unreadable I think. We can discuss how to improve it 
in Wed's T/C.

Presumably, in reality there are far less links than the stoichiometry 
expansion is creating?

One possibly would be not to do the stoich expansion - if you look at 
this example in the projects demo file and untick the expansion checkbox 
I think it is much easier to read?

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
I see this is still a problem (despite the previous attempt to reduce initialisation time).

**Comment by colin-combe** [comment]
I think we should change this so that if there is a stoichiometry of, say, more than 12 it doesn't do the expansion.

And also do this for the version 1 milestone (as it was originally tagged) because crashing peoples browsers is going to be really annoying for them. 

At least with the unexpanded version the user will see someting, and you know there are e.g. 48 instances of something because you can read it from the label (easier than counting them in the expanded version).

What do you think?

**Comment by colin-combe** [comment]
I've changed my branch so it doesn't do the stoichiometry expansion if the maximum stoich value is above 30. You can choose to pull or not.

**Comment by joshkh** [comment]
I completely agree: browser crashing/lagging is a great way to make sure
that users don't come back to the page. I'm going to merge your branch into
Milestone 1 and we can disable it if there are any objections from the
decision makers.
