### ISSUE TITLE
Viewer does not work with some valid json data

### ISSUE THREAD

**Issue by maitesin** [MICommunity/interaction-viewer#25]
Found several examples of valid json that are not displayed in the viewer. One example is with the EBI-9008283 complex. The json provided to the viewer can be found: http://wwwdev.ebi.ac.uk/intact/complex-ws/export/EBI-9008283

**Comment by colin-combe** [comment]
> Found several examples of valid json that are not displayed in the viewer.
>

OK, pass on links to json files that aren't working and I'll try to fix 
the problems.

> One example is with the EBI-9008283 complex. The json provided to the 
> viewer can be found: 
> http://wwwdev.ebi.ac.uk/intact/complex-ws/export/EBI-9008283
>

OK - thanks. This one should be working now. The problem was that the 
viewer had never encountered the "otherFeatures" attribute before. It 
now reads this attribute.


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
Sorry - I should have said that this is fixed in the master branch of 
the colin-combe/interaction-viewer repository. It hasn't been pulled 
into MICommunity repo yet. I will make a pull request.

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
Closing? I think this is what we said in meeting - we can reopen when we find other json's that aren't working (at the moment I don't know of any).
