### ISSUE TITLE
Complex viewer still not working with some data (even when updated code deployed)

### ISSUE THREAD

**Issue by sandraorchard** [MICommunity/interaction-viewer#27]
Hi

See http://wwwdev.ebi.ac.uk/intact/complex/details/EBI-9997373 for an example.

Sandra

**Comment by colin-combe** [comment]
The complex portal web page provides the JSON data within single 
quotation marks. Consequently, it is necessary to escape single 
quotation marks in the data.

E.g.:
var data = 
'{"data":[{"object":"interactor","id":"rnacentral_URS0000348061","type":{"id":"MI:0320","name":"ribonucleic 
acid"},"organism":{"taxid":"4932","common":"yeasx","scientific":"Saccharomyces 
cerevisiae (Baker'

The data string was ended prematurely by the quote mark after the "r" of 
Baker.

I think escaping these quotes is something for Oscar's end?

EBI-9997373 <http://wwwdev.ebi.ac.uk/intact/complex/details/EBI-9997373> 
has been included as an example in my branch (where it is working), it 
still looks a bit odd because tlc1_yeast_rna has no sequence data 
provided. Downloading sequence data (from UniProt) has not yet been 
implemented. (Would UniProt contain a sequence for this?)

Col
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by maitesin** [comment]
Hi Colin,

You were right. I fix that bug and It is been deployed right now in dev.

Best regards,

Oscar

**Comment by colin-combe** [comment]
Closing, fixed now quotes are escaped.
