### ISSUE TITLE
autolayout to align things at top of svg element

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#43]
From Henning:
"*3: Can the complex be displayed to have the upper border close to the 
upper border of the graph window, rather than fully centered?*"

**Comment by colin-combe** [comment]
I don't think this is so much of an issue for the complex portal now, since the height of the containing div was reduced?

**Comment by joshkh** [comment]
The more I think about it, the more I think this should be the responsibility of the page embedding the tool. Aligning the visualization to the top of the graph is a very specific request which I don't think applies to the general population, and as you said the problem is fixed by reducing the height of the div.

A page embedding the tool could also listen to the window.onscroll event and keep the tool in view as the user scrolls vertically which might work well for long complexes in the complex portal.

**Comment by colin-combe** [comment]
I agree
