### ISSUE TITLE
Viewer does not react when call the methods autoLayout and resetZoom in an specific complex

### ISSUE THREAD

**Issue by maitesin** [MICommunity/interaction-viewer#49]
In the Complex Portal when we are showing the complex EBI-847160 the methods autoLayout and resetZoom does not work. I tried even calling them directly from the JavaScript console of Firebug but it does not react. Could you please double-check or trace what is the behaviour within the viewer?

**Comment by colin-combe** [comment]
OK, I've checked it in FireFox and Chrome and it is working for me. I think this is related to #48 and I do understand why its confusing...

Try this:
a) Click and drag on the complex (pale blue blob) - this moves the complex (and the molecules inside it). Calling autoLayout will move the molecules back to the middle. Calling resetZoom will do nothing because the pan/zoom hasn't changed.

b) Click and drag on the white background - this pans the map. Now, calling autoLayout will do nothing because the positions of the molecules haven't changed but calling resetZoom will have an effect.

Can you confirm this is the behaviour you're getting?

I think this will be fixed by just having a reset() function that calls both resetZoom() and autoLayout(), see #48.

**Comment by colin-combe** [comment]
OK, a single reset() function has been added by changes in pull #51 - try using it instead. Closing for moment.
