### ISSUE TITLE
SVG download - too jumpy

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/interaction-viewer#97]
This is just personal preference, but I don't like that the page refreshes when I click on the SVG button. I understand why this is the case.

but I don't like it.

**Comment by colin-combe** [comment]
since #71 the actual download of the SVG is outside viewer, 

as far as i know there is no purely client side solution that works on desktop macs, see https://github.com/MICommunity/interaction-viewer/issues/71#issuecomment-157691145

the viewer just provides the SVG when asked: https://github.com/MICommunity/interaction-viewer/blob/master/src/controller/Controller.js#L1094-L1102

Max has added the following code to Complex Portal for download:
```
function exportSVG() {
    var xml = xlv.getSVG();
    var xmlAsUrl = 'data:image/svg;filename=xiNET-output.svg,';
    xmlAsUrl += encodeURIComponent(xml);
    window.open(xmlAsUrl, 'xiNET-output.svg');
}
```
I think changes to this land on the Complex Portal issue list,
closing...
